import {
  AppWindowIcon,
  AppWindowMacIcon,
  ArrowDown01Icon,
  ArrowUpDownIcon,
  CircleAlertIcon,
  CircleCheckIcon,
  FilePenLineIcon,
  HeadingIcon,
  ImageIcon,
  LayoutGridIcon,
  LayoutPanelLeftIcon,
  Link2Icon,
  ListChecksIcon,
  ListIcon,
  ListTreeIcon,
  LoaderCircleIcon,
  MessageSquareIcon,
  MessageSquareWarningIcon,
  RectangleEllipsisIcon,
  SearchIcon,
  Settings2Icon,
  SpeechIcon,
  SquareCheckIcon,
  SquareMenuIcon,
  SquareMousePointerIcon,
  TableIcon,
  TextCursorInputIcon,
  ToggleRightIcon,
} from 'lucide-react'
import { AriaRole, ReactNode } from 'react'

import { GetByRoleSelector } from '@/codegen/browser/selectors'

/**
 * The complete list of ARIA roles. Fill in icons as needed. If no specific icon is
 * defined for a role, a generic SpeechIcon will be used.
 */
const icons: { [P in AriaRole]: ReactNode } = {
  alert: <CircleAlertIcon />,
  alertdialog: <MessageSquareWarningIcon />,
  application: undefined,
  article: undefined,
  banner: undefined,
  button: <SquareMousePointerIcon />,
  cell: <TableIcon />,
  checkbox: <SquareCheckIcon />,
  columnheader: <TableIcon />,
  combobox: <ListChecksIcon />,
  complementary: undefined,
  contentinfo: undefined,
  definition: undefined,
  dialog: <AppWindowIcon />,
  directory: undefined,
  document: undefined,
  feed: undefined,
  figure: undefined,
  form: <FilePenLineIcon />,
  grid: <LayoutGridIcon />,
  gridcell: <LayoutGridIcon />,
  group: undefined,
  heading: <HeadingIcon />,
  img: <ImageIcon />,
  link: <Link2Icon />,
  list: <ListIcon />,
  listbox: <ListChecksIcon />,
  listitem: <ListIcon />,
  log: undefined,
  main: undefined,
  marquee: undefined,
  math: undefined,
  menu: <SquareMenuIcon />,
  menubar: <RectangleEllipsisIcon />,
  menuitem: <SquareMenuIcon />,
  menuitemcheckbox: <SquareCheckIcon />,
  menuitemradio: <CircleCheckIcon />,
  navigation: undefined,
  none: undefined,
  note: undefined,
  option: <ListChecksIcon />,
  presentation: undefined,
  progressbar: <LoaderCircleIcon />,
  radio: <CircleCheckIcon />,
  radiogroup: <CircleCheckIcon />,
  region: undefined,
  row: <TableIcon />,
  rowgroup: <TableIcon />,
  rowheader: <TableIcon />,
  scrollbar: <ArrowUpDownIcon />,
  search: <SearchIcon />,
  searchbox: <SearchIcon />,
  separator: undefined,
  slider: <Settings2Icon />,
  spinbutton: <ArrowDown01Icon />,
  status: undefined,
  switch: <ToggleRightIcon />,
  tab: <AppWindowMacIcon />,
  table: <TableIcon />,
  tablist: <AppWindowMacIcon />,
  tabpanel: <AppWindowMacIcon />,
  term: undefined,
  textbox: <TextCursorInputIcon />,
  timer: undefined,
  toolbar: <RectangleEllipsisIcon />,
  tooltip: <MessageSquareIcon />,
  tree: <ListTreeIcon />,
  treegrid: <LayoutPanelLeftIcon />,
  treeitem: <ListTreeIcon />,
}

interface RoleSelectorIconProps {
  selector: GetByRoleSelector
}

export function RoleSelectorIcon({ selector }: RoleSelectorIconProps) {
  return icons[selector.role] ?? <SpeechIcon />
}
