name: 'Setup release environment'
description: 'Checkout repo, setup Node and Python, install dependencies, and load secrets for release builds'

runs:
  using: 'composite'
  steps:
    - id: get-secrets
      uses: grafana/shared-workflows/actions/get-vault-secrets@5d7e361bc7e0a183cde8afe9899fb7b596d2659b # v1.2.0
      with:
        repo_secrets: |
          APPLE_CERTIFICATE_P12=apple-certificates:APPLE_CERTIFICATE_P12
          CERTIFICATE_PASSWORD=apple-certificates:APPLE_CERTIFICATE_P12_PASSWORD
          APPLE_API_KEY_ID=apple-certificates:APPLE_API_KEY_ID
          APPLE_API_ISSUER=apple-certificates:APPLE_API_ISSUER
          APPLE_API_KEY=apple-certificates:APPLE_API_KEY
          SENTRY_DSN=sentry:SENTRY_DSN
          SENTRY_AUTH_TOKEN=sentry:SENTRY_AUTH_TOKEN

    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      with:
        persist-credentials: false

    - name: setup node
      uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5
      with:
        node-version: 22

    # try earlier python version for appdmg
    # https://github.com/electron/forge/issues/3371#issuecomment-2105195302
    - name: Install Python 3.11.4
      uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6
      with:
        python-version: '3.11.4'

    - name: install dependencies
      run: npm ci
      shell: bash
