# Reqired by Electron Forge
nodeLinker: hoisted

# Electron Forge uses an old version of @electron/rebuild which has a github dependency on
# the now deprecated @electron/node-gyp. Until Electron Forge updates the dependency (which
# will probably not happen until 8.0.0) we need to have this disabled.
blockExoticSubdeps: false

allowBuilds:
  '@sentry/cli': true
  electron: true
  electron-winstaller: true
  esbuild: true
  fs-xattr: true
  macos-alias: true
  unrs-resolver: true

overrides:
  'esbuild': '^0.27.0'
  'nan': '^2.25.0'
  'basic-ftp': '^5.2.0'
  'tar': '^7.5.13'
  'dompurify': '^3.4.0'

patchedDependencies:
  rrweb: patches/rrweb.patch
