export {
  BrowserTestFileSchema as BrowserTestFileDataSchema,
  type BrowserTestFile,
  type AnyBrowserAction,
  type LocatorCheckAction,
  type LocatorClearAction,
  type LocatorClickAction,
  type LocatorClickButton,
  type LocatorClickModifier,
  type LocatorDoubleClickAction,
  type LocatorFillAction,
  type LocatorFocusAction,
  type LocatorHoverAction,
  type LocatorPressAction,
  type LocatorSelectOptionAction,
  type LocatorSetCheckedAction,
  type LocatorTapAction,
  type LocatorTypeAction,
  type LocatorUncheckAction,
  type LocatorWaitForAction,
  type PageGotoAction,
  type PageReloadAction,
  type PageWaitForNavigationAction,
  type PageWaitForTimeoutAction,
} from './v1'

export * from './v1/testOptions'
