// Generated by Grafana k6 Studio (0.0.0-vitest) on 2023-10-01T00:00:00.000Z

export const options = {
  scenarios: {
    default: {
      executor: "ramping-vus",
      stages: [
        { target: 5, duration: "30s" },
        { target: 0, duration: "15s" },
      ],
    },
  },
  cloud: {
    distribution: {
      'amazon:us:columbus': { loadZone: "amazon:us:columbus", percent: 60 },
      'amazon:de:frankfurt': { loadZone: "amazon:de:frankfurt", percent: 40 },
    },
  },
  thresholds: { browser_web_vital_lcp: ["p(95)<1000"] },
};

export default function () {}
