// Generated by Grafana k6 Studio (0.0.0-vitest) on 2023-10-01T00:00:00.000Z

import { browser } from "k6/browser";

export const options = {
  scenarios: {
    default: {
      executor: "shared-iterations",
      options: { browser: { type: "chromium" } },
    },
  },
};

export default async function () {
  const page = await browser.newPage();

  try {
    await page.goto("https://example.com/start");

    await Promise.all([
      page.waitForNavigation(),
      page.locator("a.nav-link").click(),
    ]);

    await page.locator('input[name="query"]').fill("search term");
  } finally {
    await page?.close();
  }
}
