// Generated by Grafana k6 Studio (0.0.0-vitest) on 2023-10-01T00:00:00.000Z

import { browser } from "k6/browser";

export const options = {
  scenarios: {
    default: {
      executor: "shared-iterations",
      options: { browser: { type: "chromium" } },
    },
  },
};

export default async function () {
  const page1 = await browser.newPage();

  try {
    await page1.goto("https://example.com");
  } finally {
    await page1?.close();
  }

  const page2 = await browser.newPage();

  try {
    await page2.goto("https://example.com");
  } finally {
    await page2?.close();
  }
}
