name: Bug report
description: Use this template for reporting bugs. Please search existing issues first.
labels: needs-triage
type: Bug
body:
  - type: textarea
    attributes:
      label: Describe the bug
  - type: textarea
    attributes:
      label: Steps to reproduce the problem
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    attributes:
      label: Actual behavior
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Grafana k6 Studio version
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: OS
      description: e.g. Windows 11, Arch Linux, macOS 15.3.1, etc.
