name: Bug report
description: Use this template for reporting bugs. Please search existing issues first.
labels: bug, needs-triage
body:
  - type: markdown
    attributes:
      value: '## Detailed issue description'
  - type: textarea
    attributes:
      label: Steps to reproduce the problem
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behaviour
    validations:
      required: true
  - type: textarea
    attributes:
      label: Actual behaviour
    validations:
      required: true
  - type: markdown
    attributes:
      value: '## Environment'
  - type: input
    attributes:
      label: Grafana k6 Studio version
    validations:
      required: true
  - type: input
    attributes:
      label: OS
      description: e.g. Windows 11, Arch Linux, macOS 15.3.1, etc.
