import {
  AppWindowIcon,
  AppWindowMacIcon,
  ArrowDown01Icon,
  ArrowUpDownIcon,
  CircleAlertIcon,
  CircleCheckIcon,
  FilePenLineIcon,
  HeadingIcon,
  ImageIcon,
  LayoutGridIcon,
  LayoutPanelLeftIcon,
  Link2Icon,
  ListChecksIcon,
  ListIcon,
  ListTreeIcon,
  LoaderCircleIcon,
  LucideProps,
  MessageSquareIcon,
  MessageSquareWarningIcon,
  RectangleEllipsisIcon,
  SearchIcon,
  Settings2Icon,
  SpeechIcon,
  SquareCheckIcon,
  SquareMenuIcon,
  SquareMousePointerIcon,
  TableIcon,
  TextCursorInputIcon,
  ToggleRightIcon,
} from 'lucide-react'
import { AriaRole, ComponentType } from 'react'

import { GetByRoleSelector } from '@/codegen/browser/selectors'

/**
 * The complete list of ARIA roles. Fill in icons as needed. If no specific icon is
 * defined for a role, a generic SpeechIcon will be used.
 */
const icons: { [P in AriaRole]: ComponentType<LucideProps> | null } = {
  alert: CircleAlertIcon,
  alertdialog: MessageSquareWarningIcon,
  application: null,
  article: null,
  banner: null,
  button: SquareMousePointerIcon,
  cell: TableIcon,
  checkbox: SquareCheckIcon,
  columnheader: TableIcon,
  combobox: ListChecksIcon,
  complementary: null,
  contentinfo: null,
  definition: null,
  dialog: AppWindowIcon,
  directory: null,
  document: null,
  feed: null,
  figure: null,
  form: FilePenLineIcon,
  grid: LayoutGridIcon,
  gridcell: LayoutGridIcon,
  group: null,
  heading: HeadingIcon,
  img: ImageIcon,
  link: Link2Icon,
  list: ListIcon,
  listbox: ListChecksIcon,
  listitem: ListIcon,
  log: null,
  main: null,
  marquee: null,
  math: null,
  menu: SquareMenuIcon,
  menubar: RectangleEllipsisIcon,
  menuitem: SquareMenuIcon,
  menuitemcheckbox: SquareCheckIcon,
  menuitemradio: CircleCheckIcon,
  navigation: null,
  none: null,
  note: null,
  option: ListChecksIcon,
  presentation: null,
  progressbar: LoaderCircleIcon,
  radio: CircleCheckIcon,
  radiogroup: CircleCheckIcon,
  region: null,
  row: TableIcon,
  rowgroup: TableIcon,
  rowheader: TableIcon,
  scrollbar: ArrowUpDownIcon,
  search: SearchIcon,
  searchbox: SearchIcon,
  separator: null,
  slider: Settings2Icon,
  spinbutton: ArrowDown01Icon,
  status: null,
  switch: ToggleRightIcon,
  tab: AppWindowMacIcon,
  table: TableIcon,
  tablist: AppWindowMacIcon,
  tabpanel: AppWindowMacIcon,
  term: null,
  textbox: TextCursorInputIcon,
  timer: null,
  toolbar: RectangleEllipsisIcon,
  tooltip: MessageSquareIcon,
  tree: ListTreeIcon,
  treegrid: LayoutPanelLeftIcon,
  treeitem: ListTreeIcon,
}

interface RoleLocatorIconProps extends LucideProps {
  selector: GetByRoleSelector
}

export function RoleLocatorIcon({ selector, ...props }: RoleLocatorIconProps) {
  const Component = icons[selector.role] ?? SpeechIcon

  return <Component {...props} />
}
