import { canonicalHeaderKey } from '@/rules/utils'
import { ProxyData } from '@/types'
import { getUpgradeHeader } from '@/utils/headers'

const HEADERS_TO_EXCLUDE = ['Cookie', 'User-Agent', 'Host', 'Content-Length']

// TODO: find a well-maintained library for this
export function stringify(value: unknown): string {
  if (typeof value === 'string') {
    return `'${value}'`
  }

  if (Array.isArray(value)) {
    return `[${value.map(stringify).join(', ')}]`
  }

  if (typeof value === 'object' && value !== null) {
    const properties = Object.entries(value)
      .filter(([, value]) => value !== undefined)
      .map(([key, value]) => `${key}: ${stringify(value)}`)
      .join(',\n')

    return `{${properties}}`
  }

  // TODO: https://github.com/grafana/k6-studio/issues/277
  // eslint-disable-next-line @typescript-eslint/restrict-template-expressions
  return `${value}`
}

export const removeWebsocketRequests = (recording: ProxyData[]) => {
  return recording.filter((data) => {
    return getUpgradeHeader(data.request.headers) !== 'websocket'
  })
}

export function cleanupRecording(recording: ProxyData[]) {
  return removeWebsocketRequests(recording)
}

export function shouldIncludeHeaderInScript(key: string) {
  return !HEADERS_TO_EXCLUDE.includes(canonicalHeaderKey(key))
}

export function generateScriptHeader() {
  return `Generated by Grafana k6 Studio (${__APP_VERSION__}) on ${new Date().toISOString()}`
}
