// Generated by Grafana k6 Studio (0.0.0-vitest) on 2023-10-01T00:00:00.000Z

import { browser } from "k6/browser";
import { expect } from "https://jslib.k6.io/k6-testing/0.5.0/index.js";

export const options = {
  scenarios: {
    default: {
      executor: "shared-iterations",
      options: { browser: { type: "chromium" } },
    },
  },
};

export default async function () {
  const page = await browser.newPage();

  await expect(page.locator('input[type="checkbox"]')).toBeChecked({
    indeterminate: true,
  });
}
