name: 'Manual Release'

on:
  workflow_dispatch:

permissions: {}

jobs:
  release:
    permissions:
      contents: write
      id-token: write
    uses: ./.github/workflows/release-base.yml
    secrets: inherit
