name: Release Please

on:
  push:
    branches:
      - main

permissions: {}

jobs:
  release-please:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@a02a34c4d625f9be7cb89156071d8567266a2445
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN}}
